// This file was auto-generated by Fern from our API Definition.

export interface GetVerificationUrlUbosResponse {
    data?: GetVerificationUrlUbosResponse.Data | undefined;
    /** Unique identifier for the API request */
    requestId?: number | undefined;
}

export namespace GetVerificationUrlUbosResponse {
    export interface Data {
        /** The most recent selfie verification session for the UBO, or `null` if no session exists yet. */
        latestSession?: (Data.LatestSession | null) | undefined;
        /** Older selfie verification sessions for the UBO in reverse chronological order. */
        previousSessions?: Data.PreviousSessions.Item[] | undefined;
    }

    export namespace Data {
        /**
         * The most recent selfie verification session for the UBO, or `null` if no session exists yet.
         */
        export interface LatestSession {
            /** Selfie verification URL for the current session. */
            kycLink?: string | undefined;
            /** Current status of the selfie verification session. */
            status?: LatestSession.Status | undefined;
            /** Session expiry timestamp in milliseconds since Unix epoch. */
            expiryTimestamp?: number | undefined;
            /** Session creation timestamp in milliseconds since Unix epoch. */
            createdTimestamp?: number | undefined;
        }

        export namespace LatestSession {
            /** Current status of the selfie verification session. */
            export const Status = {
                NotStarted: "NOT_STARTED",
                Running: "RUNNING",
                Pending: "PENDING",
                Approved: "APPROVED",
                Declined: "DECLINED",
                Expired: "EXPIRED",
            } as const;
            export type Status = (typeof Status)[keyof typeof Status];
        }

        export type PreviousSessions = PreviousSessions.Item[];

        export namespace PreviousSessions {
            export interface Item {
                /** Selfie verification URL for the session. */
                kycLink?: string | undefined;
                /** Status of the selfie verification session. */
                status?: Item.Status | undefined;
                /** Session expiry timestamp in milliseconds since Unix epoch. */
                expiryTimestamp?: number | undefined;
                /** Session creation timestamp in milliseconds since Unix epoch. */
                createdTimestamp?: number | undefined;
            }

            export namespace Item {
                /** Status of the selfie verification session. */
                export const Status = {
                    NotStarted: "NOT_STARTED",
                    Running: "RUNNING",
                    Pending: "PENDING",
                    Approved: "APPROVED",
                    Declined: "DECLINED",
                    Expired: "EXPIRED",
                } as const;
                export type Status = (typeof Status)[keyof typeof Status];
            }
        }
    }
}
