// This file was auto-generated by Fern from our API Definition.

export const ListAccountsRequestSortOrder = {
    Asc: "ASC",
    Desc: "DESC",
} as const;
export type ListAccountsRequestSortOrder =
    (typeof ListAccountsRequestSortOrder)[keyof typeof ListAccountsRequestSortOrder];
