// This file was auto-generated by Fern from our API Definition.

export interface DeleteDocumentsResponse {
    /** Success message */
    message?: string | undefined;
    /** The ID of the request */
    requestId?: number | undefined;
}
