// This file was auto-generated by Fern from our API Definition.

export const GetBeneficiariesRequestOwnerType = {
    Individual: "individual",
    Business: "business",
} as const;
export type GetBeneficiariesRequestOwnerType =
    (typeof GetBeneficiariesRequestOwnerType)[keyof typeof GetBeneficiariesRequestOwnerType];
