// This file was auto-generated by Fern from our API Definition.

import type * as Mesta from "../../../../../index.js";

export interface ListPaymentTypesBeneficiariesResponse {
    data?: ListPaymentTypesBeneficiariesResponse.Data | undefined;
    /** Unique identifier for the API request */
    requestId?: number | undefined;
}

export namespace ListPaymentTypesBeneficiariesResponse {
    export interface Data {
        /** Unique identifier for the payment types rules */
        id?: string | undefined;
        /** Version number of the rules */
        version?: number | undefined;
        /** Timestamp when the rules were created (ISO 8601) */
        createdAt?: string | undefined;
        /** Timestamp when the rules were last updated (ISO 8601) */
        updatedAt?: string | undefined;
        /** Timestamp when the rules were deleted, if applicable (ISO 8601) */
        deletedAt?: (string | null) | undefined;
        /** Identifier of the user who created the rules */
        createdBy?: string | undefined;
        /** Identifier of the user who last updated the rules */
        updatedBy?: string | undefined;
        /** Identifier of the user who deleted the rules */
        deletedBy?: (string | null) | undefined;
        /** Type of entity these rules apply to */
        owner?: Data.Owner | undefined;
        /** Category of the beneficiary */
        ownerType?: Data.OwnerType | undefined;
        /** Two-letter country code (ISO 3166-1 alpha-2) */
        country?: string | undefined;
        rules?: Data.Rules | undefined;
    }

    export namespace Data {
        /** Type of entity these rules apply to */
        export const Owner = {
            Beneficiary: "beneficiary",
        } as const;
        export type Owner = (typeof Owner)[keyof typeof Owner];
        /** Category of the beneficiary */
        export const OwnerType = {
            Individual: "individual",
            Business: "business",
        } as const;
        export type OwnerType = (typeof OwnerType)[keyof typeof OwnerType];

        export interface Rules {
            /** List of supported payment types for the country */
            paymentTypes?: Rules.PaymentTypes.Item[] | undefined;
        }

        export namespace Rules {
            export type PaymentTypes = PaymentTypes.Item[];

            export namespace PaymentTypes {
                export interface Item {
                    /** Payment method type */
                    type?: Item.Type | undefined;
                    /** Human-readable description of payment type */
                    description?: string | undefined;
                    /** List of required fields for this payment type */
                    requiredFields?: Mesta.ValidationField[] | undefined;
                }

                export namespace Item {
                    /** Payment method type */
                    export const Type = {
                        Pix: "pix",
                        Instapay: "instapay",
                        SwiftpayPesonet: "swiftpay_pesonet",
                        Spei: "spei",
                        BankAccount: "bank_account",
                        CryptoWallet: "crypto_wallet",
                        MobileMoney: "mobile_money",
                    } as const;
                    export type Type = (typeof Type)[keyof typeof Type];
                }
            }
        }
    }
}
