// This file was auto-generated by Fern from our API Definition.

export interface ListCountriesBeneficiariesResponse {
    data?: string[] | undefined;
    /** Unique identifier for the API request */
    requestId?: number | undefined;
}
