// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface DeleteUbosRequest {
    /** Unique identifier of the UBO */
    id: string;
}
