// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface DeleteWebhooksRequest {
    /** Unique identifier for the webhook to be deleted. */
    id: string;
}
