// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         merchantId: "merchantId"
 *     }
 */
export interface AcceptTermsMerchantsRequest {
    /** ID of the merchant */
    merchantId: string;
}
