// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         currency: "EUR"
 *     }
 */
export interface GenerateEurGbpDepositBankAccountsRequest {
    /** ID of the sender */
    id: string;
    /** The currency for the deposit bank account. Only EUR and GBP are supported. */
    currency: GenerateEurGbpDepositBankAccountsRequest.Currency;
}

export namespace GenerateEurGbpDepositBankAccountsRequest {
    /** The currency for the deposit bank account. Only EUR and GBP are supported. */
    export const Currency = {
        Eur: "EUR",
        Gbp: "GBP",
    } as const;
    export type Currency = (typeof Currency)[keyof typeof Currency];
}
