// This file was auto-generated by Fern from our API Definition.

/**
 * Postal address.
 */
export interface Address {
    /** Street address. */
    street: string;
    /** Additional street address line. */
    street2?: string | undefined;
    /** City. */
    city: string;
    /** State or province (ISO 3166-2 format, e.g. US-CA). */
    state?: string | undefined;
    /** Postal/ZIP code. Use '00000' for countries without postal code systems */
    postalCode: string;
    /** Country. */
    country: string;
}
