// This file was auto-generated by Fern from our API Definition.

import type * as Mesta from "../index.js";

export interface BusinessSender {
    /** Type of the sender. */
    type: BusinessSender.Type;
    /** Legal business name. */
    fullName: string;
    /** Email address of the sender. */
    email: string;
    /** A phone number in international format (e.g., +11234567890). */
    phone: string;
    /** Array of addresses for the sender. */
    addresses: Mesta.Address[];
    /** Date when the business was registered (ISO 8601 format: YYYY-MM-DD) */
    registrationDate: string;
    /** Type of business entity */
    businessType: BusinessSender.BusinessType;
    /** Website URL of the individual or business. */
    websiteUrl?: string | undefined;
    /** Business registration number issued by the sender's country of registration. */
    identificationNumber: string | null;
    /** Business tax identification number. This field is optional in the generic sender schema and becomes required when a selected capability requires it. */
    taxIdentificationNumber?: (string | null) | undefined;
    /** Additional custom metadata for the sender account. */
    metadata?: Record<string, unknown> | undefined;
    /** Merchant ID (optional, auto-assigned from API key) */
    merchantId?: string | undefined;
}

export namespace BusinessSender {
    /** Type of the sender. */
    export const Type = {
        Business: "business",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    /** Type of business entity */
    export const BusinessType = {
        SoleProprietorship: "sole_proprietorship",
        Partnership: "partnership",
        Corporation: "corporation",
        LimitedLiabilityCompany: "limited_liability_company",
        Other: "other",
    } as const;
    export type BusinessType = (typeof BusinessType)[keyof typeof BusinessType];
}
