// This file was auto-generated by Fern from our API Definition.

import type * as Mesta from "../index.js";

/**
 * Partial update payload for a business sender. Include only the fields you want to change.
 */
export interface PatchBusinessSender {
    /** Legal business name. */
    fullName?: string | undefined;
    email?: string | undefined;
    /** Phone number in international format. */
    phone?: string | undefined;
    addresses?: Mesta.Address[] | undefined;
    websiteUrl?: string | undefined;
    metadata?: Record<string, unknown> | undefined;
    registrationDate?: string | undefined;
    businessType?: PatchBusinessSender.BusinessType | undefined;
    isFinancialInstitution?: boolean | undefined;
    websiteAbsenceReason?: string | undefined;
    numberOfEmployees?: PatchBusinessSender.NumberOfEmployees | undefined;
    expectedMonthlyVolumeEstimate?: number | undefined;
    averageTransactionSize?: number | undefined;
    primaryCounterpartyJurisdictions?: string[] | undefined;
    natureOfPayments?: string[] | undefined;
    sourceOfFunds?: string | undefined;
    /** Provider-specific credentials for the sender. */
    providerCredentials?: Record<string, unknown> | undefined;
    /** External reference identifiers for the sender. */
    externalRefs?: Record<string, unknown> | undefined;
}

export namespace PatchBusinessSender {
    export const BusinessType = {
        SoleProprietorship: "sole_proprietorship",
        Partnership: "partnership",
        Corporation: "corporation",
        LimitedLiabilityCompany: "limited_liability_company",
        Other: "other",
    } as const;
    export type BusinessType = (typeof BusinessType)[keyof typeof BusinessType];
    export const NumberOfEmployees = {
        One: "1",
        Two10: "2-10",
        Eleven50: "11-50",
        FiftyOne200: "51-200",
        TwoHundredOne1000: "201-1000",
        OneThousand: "1000+",
        Unknown: "unknown",
    } as const;
    export type NumberOfEmployees = (typeof NumberOfEmployees)[keyof typeof NumberOfEmployees];
}
