// This file was auto-generated by Fern from our API Definition.

import type * as Mesta from "../index.js";

/**
 * Payment method object
 */
export interface PaymentMethod {
    /** Unique payment method ID */
    id?: string | undefined;
    /** Associated beneficiary ID */
    beneficiaryId?: string | undefined;
    /** Associated merchant ID */
    merchantId?: string | undefined;
    type?: Mesta.PaymentMethodType | undefined;
    status?: Mesta.PaymentMethodStatus | undefined;
    /** Display label for the payment method */
    label?: (string | null) | undefined;
    /** Payment method data. Structure depends on type field. */
    data?: Mesta.PaymentMethodData | undefined;
    /** Creation timestamp */
    createdAt?: string | undefined;
    /** Last update timestamp */
    updatedAt?: string | undefined;
    /** Version number for optimistic locking */
    version?: number | undefined;
}
