// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         token: "token"
 *     }
 */
export interface AcceptTermsOfServiceRequest {
    /** TOS acceptance token (base64url encoded) */
    token: string;
}
