// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface CreateLinkTermsOfServiceRequest {
    /** ID of the sender */
    id: string;
    /** When true, forces generation of a new TOS link even if one already exists */
    regenerate?: boolean;
}
