// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         beneficiaryId: "beneficiaryId"
 *     }
 */
export interface VerifyBeneficiariesRequest {
    /** Unique identifier for the beneficiary. */
    beneficiaryId: string;
}
