// This file was auto-generated by Fern from our API Definition.

export const ListAccountsRequestSortBy = {
    CreatedAt: "createdAt",
    UpdatedAt: "updatedAt",
} as const;
export type ListAccountsRequestSortBy = (typeof ListAccountsRequestSortBy)[keyof typeof ListAccountsRequestSortBy];
