// This file was auto-generated by Fern from our API Definition.

export const ListBeneficiariesRequestSortOrder = {
    Asc: "ASC",
    Desc: "DESC",
} as const;
export type ListBeneficiariesRequestSortOrder =
    (typeof ListBeneficiariesRequestSortOrder)[keyof typeof ListBeneficiariesRequestSortOrder];
