// This file was auto-generated by Fern from our API Definition.

export interface GenerateDepositWalletAddressesResponse {
    data?: GenerateDepositWalletAddressesResponse.Data.Item[] | undefined;
    /** Unique identifier for the API request */
    requestId?: number | undefined;
}

export namespace GenerateDepositWalletAddressesResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            id?: string | undefined;
            /** Blockchain wallet address */
            address?: string | undefined;
            chain?: Item.Chain | undefined;
            ownerId?: string | undefined;
            ownerType?: Item.OwnerType | undefined;
            /** Wallet provider */
            provider?: string | undefined;
        }

        export namespace Item {
            export const Chain = {
                Ethereum: "ethereum",
                Solana: "solana",
                Polygon: "polygon",
                Tron: "tron",
                Stellar: "stellar",
            } as const;
            export type Chain = (typeof Chain)[keyof typeof Chain];
            export const OwnerType = {
                Merchant: "merchant",
            } as const;
            export type OwnerType = (typeof OwnerType)[keyof typeof OwnerType];
        }
    }
}
