// This file was auto-generated by Fern from our API Definition.

export const ListV1BeneficiariesRequestSortOrder = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type ListV1BeneficiariesRequestSortOrder =
    (typeof ListV1BeneficiariesRequestSortOrder)[keyof typeof ListV1BeneficiariesRequestSortOrder];
