// This file was auto-generated by Fern from our API Definition.

export const ListV2BeneficiariesRequestSortBy = {
    CreatedAt: "createdAt",
    UpdatedAt: "updatedAt",
} as const;
export type ListV2BeneficiariesRequestSortBy =
    (typeof ListV2BeneficiariesRequestSortBy)[keyof typeof ListV2BeneficiariesRequestSortBy];
