// This file was auto-generated by Fern from our API Definition.

import type * as Mesta from "../../../index.js";

export interface UpdateV1BeneficiariesResponse {
    data?: UpdateV1BeneficiariesResponse.Data | undefined;
    /** Unique identifier for the API request */
    requestId?: number | undefined;
}

export namespace UpdateV1BeneficiariesResponse {
    export interface Data {
        /** Unique identifier for the beneficiary */
        id?: string | undefined;
        /** Version number of the beneficiary record */
        version?: number | undefined;
        /** Timestamp when the beneficiary was created */
        createdAt?: string | undefined;
        /** Timestamp when the beneficiary was last updated */
        updatedAt?: string | undefined;
        /** Timestamp when the beneficiary was deleted */
        deletedAt?: (string | null) | undefined;
        /** ID of the user who created the beneficiary */
        createdBy?: (string | null) | undefined;
        /** ID of the user who last updated the beneficiary */
        updatedBy?: string | undefined;
        /** ID of the user who deleted the beneficiary */
        deletedBy?: (string | null) | undefined;
        /** Type of beneficiary */
        type?: Data.Type | undefined;
        /** First name (for individual beneficiaries) */
        firstName?: (string | null) | undefined;
        /** Last name (for individual beneficiaries) */
        lastName?: (string | null) | undefined;
        /** Middle name (for individual beneficiaries) */
        middleName?: (string | null) | undefined;
        /** Full name of the business or individual */
        fullName?: string | undefined;
        /** Date of birth (for individual beneficiaries) */
        birthDate?: (string | null) | undefined;
        /** Email address */
        email?: (string | null) | undefined;
        /** Phone number in E.164 format */
        phone?: (string | null) | undefined;
        /** Address information */
        address?: Data.Address | undefined;
        /** Identifier of the associated merchant */
        merchantId?: string | undefined;
        /** Verification information */
        verification?: Data.Verification | undefined;
        /** Indicates whether the beneficiary is currently active or inactive. */
        status?: Data.Status | undefined;
        paymentType?: Mesta.PaymentMethodType | undefined;
        /** Payment method details */
        paymentInfo?: Data.PaymentInfo | undefined;
        /** Identity document information (required for certain countries) */
        identity?: Data.Identity | undefined;
        /** Type of business entity (for business beneficiaries) */
        businessType?: Data.BusinessType | undefined;
        /** Business registration number */
        businessRegistrationNumber?: string | undefined;
        /** Custom key-value metadata attached to this beneficiary */
        metadata?: (Record<string, unknown> | null) | undefined;
    }

    export namespace Data {
        /** Type of beneficiary */
        export const Type = {
            Individual: "individual",
            Business: "business",
        } as const;
        export type Type = (typeof Type)[keyof typeof Type];

        /**
         * Address information
         */
        export interface Address {
            /** Street address */
            street?: string | undefined;
            /** Additional street address information */
            street2?: (string | null) | undefined;
            /** City name */
            city?: string | undefined;
            /** State/province code */
            state?: string | undefined;
            /** Two-letter country code */
            country?: string | undefined;
            /** Postal/ZIP code */
            postalCode?: string | undefined;
        }

        /**
         * Verification information
         */
        export interface Verification {
            /** Verification status */
            status?: Verification.Status | undefined;
            /** Timestamp of the last verification status update */
            statusUpdatedAt?: string | undefined;
        }

        export namespace Verification {
            /** Verification status */
            export const Status = {
                Unverified: "unverified",
                Pending: "pending",
                Approved: "approved",
                Declined: "declined",
            } as const;
            export type Status = (typeof Status)[keyof typeof Status];
        }

        /** Indicates whether the beneficiary is currently active or inactive. */
        export const Status = {
            Active: "active",
            Inactive: "inactive",
        } as const;
        export type Status = (typeof Status)[keyof typeof Status];
        /**
         * Payment method details
         */
        export type PaymentInfo =
            | Mesta.BankAccount
            | Mesta.PixInfo
            | Mesta.SwiftpayPesonetInfo
            | Mesta.InstapayInfo
            | Mesta.SpeiInfo
            | Mesta.MobileMoneyInfo
            | Mesta.CryptoWalletInfo;

        /**
         * Identity document information (required for certain countries)
         */
        export interface Identity {
            /** Type of identity document */
            documentType?: (Identity.DocumentType | null) | undefined;
            /** Two-letter country code of the identity document */
            countryCode?: (string | null) | undefined;
            /** Document identification number */
            documentNumber?: (string | null) | undefined;
            /** Issue date of the identity document (YYYY-MM-DD) */
            issueDate?: (string | null) | undefined;
            /** Expiry date of the identity document (YYYY-MM-DD) */
            expiryDate?: (string | null) | undefined;
            /** Issuing authority of the identity document */
            issuer?: (string | null) | undefined;
        }

        export namespace Identity {
            /** Type of identity document */
            export const DocumentType = {
                Passport: "PASSPORT",
                DriverLicense: "DRIVER_LICENSE",
                NationalId: "NATIONAL_ID",
                IdCard: "ID_CARD",
                ResidentCard: "RESIDENT_CARD",
                TaxId: "TAX_ID",
                VoterIdCard: "VOTER_ID_CARD",
            } as const;
            export type DocumentType = (typeof DocumentType)[keyof typeof DocumentType];
        }

        /** Type of business entity (for business beneficiaries) */
        export const BusinessType = {
            SoleProprietorship: "sole_proprietorship",
            Partnership: "partnership",
            Corporation: "corporation",
            LimitedLiabilityCompany: "limited_liability_company",
            Other: "other",
        } as const;
        export type BusinessType = (typeof BusinessType)[keyof typeof BusinessType];
    }
}
