// This file was auto-generated by Fern from our API Definition.

export interface ValidateBeneficiariesResponse {
    /** Returns true if the beneficiary is valid */
    data?: boolean | undefined;
    /** Unique identifier for the API request */
    requestId?: number | undefined;
}
