// This file was auto-generated by Fern from our API Definition.

import type * as Mesta from "../../../../../../index.js";

/**
 * @example
 *     {
 *         senderId: "7e701fe5-d47b-4e44-b624-c48204cfead1",
 *         roles: ["director"],
 *         linkedUboId: "c4de346d-7972-4139-b132-974eca8b0606"
 *     }
 *
 * @example
 *     {
 *         senderId: "7e701fe5-d47b-4e44-b624-c48204cfead1",
 *         roles: ["authorized_representative"],
 *         firstName: "Amina",
 *         lastName: "Rahman",
 *         birthDate: "1988-04-12",
 *         email: "amina.rahman@example.com",
 *         phone: "+442071838750",
 *         address: {
 *             street: "10 Example Street",
 *             city: "London",
 *             postalCode: "SW1A 1AA",
 *             country: "GB"
 *         },
 *         nationality: "GB",
 *         identity: {
 *             countryCode: "GB",
 *             documentType: "PASSPORT",
 *             documentNumber: "123456789",
 *             documentFront: "<base64-encoded-file>"
 *         }
 *     }
 */
export interface CreateSenderAssociateRequest {
    senderId: string;
    roles: Mesta.SenderAssociateRole[];
    /** Existing UBO representing the same person. Linked representatives reuse the UBO's stored data and verification session. */
    linkedUboId?: string;
    firstName?: string;
    lastName?: string;
    birthDate?: string;
    email?: string;
    phone?: string;
    address?: Mesta.SenderAssociateAddress;
    nationality?: string;
    identity?: Mesta.SenderAssociateIdentityInput;
    pepDeclaration?: boolean;
    pepQuestionnaire?: Record<string, unknown>;
    /** Base64 encoded source-of-funds document. */
    sofDocument?: string;
    /** Base64 encoded verification report. */
    verificationReport?: string;
    verificationReportFileName?: string;
}
