// This file was auto-generated by Fern from our API Definition.

export const ListSourceWalletAddressesRequestSortOrder = {
    Asc: "ASC",
    Desc: "DESC",
} as const;
export type ListSourceWalletAddressesRequestSortOrder =
    (typeof ListSourceWalletAddressesRequestSortOrder)[keyof typeof ListSourceWalletAddressesRequestSortOrder];
