// This file was auto-generated by Fern from our API Definition.

export const ListStablecoinDepositsRequestSortOrder = {
    Asc: "ASC",
    Desc: "DESC",
} as const;
export type ListStablecoinDepositsRequestSortOrder =
    (typeof ListStablecoinDepositsRequestSortOrder)[keyof typeof ListStablecoinDepositsRequestSortOrder];
