// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface AuthorizeAuthRequest {
    /** The host of the originating request */
    host?: string;
    /** The Authorization header value (Bearer token) */
    authorizationHeader?: string;
    /** List of permissions required for the request */
    permissionsRequired?: string[];
    /** Whether all permissions are required (and) or any one suffices (or) */
    permissionCheckType?: AuthorizeAuthRequest.PermissionCheckType;
    /** Whether to enforce permission checks */
    shouldAuthorize?: boolean;
    /** API key for key-based authentication */
    apiKey?: string;
    /** API secret for key-based authentication */
    apiSecret?: string;
}

export namespace AuthorizeAuthRequest {
    /** Whether all permissions are required (and) or any one suffices (or) */
    export const PermissionCheckType = {
        And: "and",
        Or: "or",
    } as const;
    export type PermissionCheckType = (typeof PermissionCheckType)[keyof typeof PermissionCheckType];
}
