// This file was auto-generated by Fern from our API Definition.

import type * as Mesta from "../../../../../../index.js";

/**
 * @example
 *     {
 *         beneficiaryId: "beneficiaryId",
 *         documentId: "documentId"
 *     }
 */
export interface GetPresignedUrlDocumentsRequest {
    /** Unique identifier of the beneficiary */
    beneficiaryId: string;
    /** Unique identifier of the document */
    documentId: string;
    /** Type of document to retrieve */
    type?: Mesta.beneficiaries.GetPresignedUrlDocumentsRequestType;
}
