// This file was auto-generated by Fern from our API Definition.

export const GetV1SendersRequestOwnerType = {
    Individual: "individual",
    Business: "business",
} as const;
export type GetV1SendersRequestOwnerType =
    (typeof GetV1SendersRequestOwnerType)[keyof typeof GetV1SendersRequestOwnerType];
