// This file was auto-generated by Fern from our API Definition.

import type * as Mesta from "../../../../../../index.js";

/**
 * @example
 *     {
 *         ownerType: "individual",
 *         country: "country"
 *     }
 */
export interface ListDocumentTypesV1SendersRequest {
    /** Type of sender entity */
    ownerType: Mesta.validationRules.ListDocumentTypesV1SendersRequestOwnerType;
    /** Two-letter ISO country code */
    country: string;
}
