// This file was auto-generated by Fern from our API Definition.

export const ListEventsRequestSortOrder = {
    Asc: "ASC",
    Desc: "DESC",
} as const;
export type ListEventsRequestSortOrder = (typeof ListEventsRequestSortOrder)[keyof typeof ListEventsRequestSortOrder];
