// This file was auto-generated by Fern from our API Definition.

import type * as Mesta from "../../../../../../index.js";

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface ListSourceWalletAddressesRequest {
    /** ID of the sender */
    id: string;
    /** Page number (0-indexed) */
    page?: number;
    /** Number of records per page */
    pageSize?: number;
    /** Field to sort by */
    sortBy?: Mesta.senders.ListSourceWalletAddressesRequestSortBy;
    /** Sort direction */
    sortOrder?: Mesta.senders.ListSourceWalletAddressesRequestSortOrder;
    /** Search query to filter results */
    search?: string;
}
