// This file was auto-generated by Fern from our API Definition.

/**
 * Fiat deposit object for detail responses (includes depositDetails)
 */
export interface FiatDepositDetail {
    /** Unique identifier for the deposit */
    id: string;
    /** Deposit amount (decimal with 2 decimal places) */
    amount: string;
    /** Fiat currency code */
    currency: FiatDepositDetail.Currency;
    /** Associated transaction ID */
    transactionId?: string | undefined;
    /** Merchant ID */
    merchantId: string;
    /** Sender ID */
    senderId?: string | undefined;
    /** Deposit bank account ID */
    depositBankAccountId: string;
    /** Creation timestamp */
    createdAt?: string | undefined;
    /** Last update timestamp */
    updatedAt?: string | undefined;
    /** Details of the deposit transaction from the bank */
    depositDetails?: (FiatDepositDetail.DepositDetails | null) | undefined;
}

export namespace FiatDepositDetail {
    /** Fiat currency code */
    export const Currency = {
        Usd: "USD",
        Eur: "EUR",
        Gbp: "GBP",
        Mxn: "MXN",
        Brl: "BRL",
    } as const;
    export type Currency = (typeof Currency)[keyof typeof Currency];

    /**
     * Details of the deposit transaction from the bank
     */
    export interface DepositDetails {
        /** Name of the depositor */
        depositorName?: (string | null) | undefined;
        /** Address of the depositor */
        depositorAddress?: (string | null) | undefined;
        /** Bank account number of the depositor */
        depositorBankAccountNumber?: (string | null) | undefined;
        /** Name of the depositor's bank */
        depositorBankName?: (string | null) | undefined;
        /** Country of the depositor's bank */
        depositorBankCountry?: (string | null) | undefined;
        /** Routing codes associated with the deposit */
        routingCodes?: (DepositDetails.RoutingCodes.Item[] | null) | undefined;
        /** Wire routing number */
        wireRoutingNumber?: (string | null) | undefined;
        /** Sort code for UK bank transfers */
        sortCode?: (string | null) | undefined;
        /** Type of payment */
        paymentType?: (string | null) | undefined;
        /** Date and time of the transaction */
        transactionDate?: (string | null) | undefined;
        /** Reference string for the transaction */
        transactionReference?: (string | null) | undefined;
    }

    export namespace DepositDetails {
        export type RoutingCodes = RoutingCodes.Item[];

        export namespace RoutingCodes {
            export interface Item {
                /** Type of routing code */
                routingCodeKey?: string | undefined;
                /** Value of the routing code */
                routingCodeValue?: string | undefined;
            }
        }
    }
}
