// This file was auto-generated by Fern from our API Definition.

/**
 * Mobile money payment method data
 */
export interface MobileMoneyInfo {
    /** Mobile phone number in international format */
    phone: string;
}
