// This file was auto-generated by Fern from our API Definition.

import type * as Mesta from "../index.js";

/**
 * Partial update payload for an individual sender. Include only the fields you want to change.
 */
export interface PatchIndividualSender {
    /** First name of the individual sender. */
    firstName?: string | undefined;
    /** Last name of the individual sender. */
    lastName?: string | undefined;
    /** Middle name of the individual sender. */
    middleName?: string | undefined;
    /** Birth date in ISO 8601 format (YYYY-MM-DD). */
    birthDate?: string | undefined;
    gender?: PatchIndividualSender.Gender | undefined;
    /** Occupation of the individual sender. */
    occupation?: string | undefined;
    email?: string | undefined;
    /** Phone number in international format. */
    phone?: string | undefined;
    addresses?: Mesta.Address[] | undefined;
    websiteUrl?: string | undefined;
    metadata?: Record<string, unknown> | undefined;
    identity?: PatchIndividualSender.Identity | undefined;
    expectedMonthlyVolumeEstimate?: number | undefined;
    averageTransactionSize?: number | undefined;
    primaryCounterpartyJurisdictions?: string[] | undefined;
    natureOfPayments?: string[] | undefined;
    sourceOfFunds?: string | undefined;
    /** Provider-specific credentials for the sender. */
    providerCredentials?: Record<string, unknown> | undefined;
    /** External reference identifiers for the sender. */
    externalRefs?: Record<string, unknown> | undefined;
}

export namespace PatchIndividualSender {
    export const Gender = {
        Male: "male",
        Female: "female",
        Other: "other",
    } as const;
    export type Gender = (typeof Gender)[keyof typeof Gender];

    export interface Identity {
        documentType?: string | undefined;
        countryCode?: string | undefined;
        documentFront?: string | undefined;
        documentBack?: string | undefined;
        documentNumber?: string | undefined;
        issueDate?: string | undefined;
        expiryDate?: string | undefined;
    }
}
