// This file was auto-generated by Fern from our API Definition.

/**
 * Purpose of payment document response
 */
export interface PurposeOfPaymentDocument {
    id?: string | undefined;
    fileName?: string | undefined;
    type?: string | undefined;
    submittedAt?: string | undefined;
}
