// This file was auto-generated by Fern from our API Definition.

/** Purpose of the transaction */
export const Purpose = {
    OperationalExpense: "operational_expense",
    VendorPayment: "vendor_payment",
    SubsidiaryTransfer: "subsidiary_transfer",
    AccountingServices: "accounting_services",
    AdministrativeExpenses: "administrative_expenses",
    BusinessProfits: "business_profits",
    FinancialLease: "financial_lease",
    FinesAndPenalties: "fines_and_penalties",
    InsurancePremium: "insurance_premium",
    InterestOnLoans: "interest_on_loans",
    LegalServices: "legal_services",
    OtherPersonalServices: "other_personal_services",
    PaymentForGoodsAndServices: "payment_for_goods_and_services",
    PilgrimageReligiousRelated: "pilgrimage_religious_related",
    ResearchAndDevelopmentServices: "research_and_development_services",
} as const;
export type Purpose = (typeof Purpose)[keyof typeof Purpose];
