
/** Purpose of payment for the beneficiary */
export const PurposeOfPayment = {
    Payroll: "payroll",
    OperationalExpense: "operational_expense",
    VendorPayment: "vendor_payment",
    SubsidiaryTransfer: "subsidiary_transfer",
    AccountingServices: "accounting_services",
    AdministrativeExpenses: "administrative_expenses",
    BusinessProfits: "business_profits",
    BusinessTravel: "business_travel",
    EducationalExpenses: "educational_expenses",
    EmployeeSalary: "employee_salary",
    FamilyMaintenanceSaving: "family_maintenance_saving",
    FinancialLease: "financial_lease",
    FinesAndPenalties: "fines_and_penalties",
    FreelancerPayment: "freelancer_payment",
    HotelExpenses: "hotel_expenses",
    InsurancePremium: "insurance_premium",
    InterestOnLoans: "interest_on_loans",
    InvestmentInRealEstate: "investment_in_real_estate",
    InvestmentInSecurities: "investment_in_securities",
    InvestmentInShares: "investment_in_shares",
    LegalServices: "legal_services",
    MedicalExpenses: "medical_expenses",
    OtherPersonalServices: "other_personal_services",
    PaymentForGoodsAndServices: "payment_for_goods_and_services",
    PersonalTravelAndTour: "personal_travel_and_tour",
    PilgrimageReligiousRelated: "pilgrimage_religious_related",
    RepaymentOfLoan: "repayment_of_loan",
    ResearchAndDevelopmentServices: "research_and_development_services",
    TaxPayment: "tax_payment",
    TelecommunicationServices: "telecommunication_services",
    WorkersRemittances: "workers_remittances",
} as const;
export type PurposeOfPayment = (typeof PurposeOfPayment)[keyof typeof PurposeOfPayment];
