
/** Source of funds for the transaction */
export const SourceOfFunds = {
    AdvanceFromDirector: "advance_from_director",
    AdvanceFromShareholder: "advance_from_shareholder",
    BusinessIncome: "business_income",
    Claims: "claims",
    Compensation: "compensation",
    FinancialSupportFromChildren: "financial_support_from_children",
    FinancialSupportFromParents: "financial_support_from_parents",
    FinancialSupportFromSpouse: "financial_support_from_spouse",
    FreelanceIncome: "freelance_income",
    Gambling: "gambling",
    Insurance: "insurance",
    InterestIncome: "interest_income",
    DividendIncome: "dividend_income",
    IssueOfBond: "issue_of_bond",
    IssueOfDebenture: "issue_of_debenture",
    IssueOfShare: "issue_of_share",
    Loans: "loans",
    PropertyInvestment: "property_investment",
    RentalIncome: "rental_income",
    LeasingIncome: "leasing_income",
    RetirementFunds: "retirement_funds",
    Salary: "salary",
    Saving: "saving",
    SalesOfAssets: "sales_of_assets",
    ShareInvestment: "share_investment",
    TaxRefund: "tax_refund",
    VentureCapital: "venture_capital",
} as const;
export type SourceOfFunds = (typeof SourceOfFunds)[keyof typeof SourceOfFunds];
