// This file was auto-generated by Fern from our API Definition.

export interface SwiftpayPesonetInfo {
    /** Channel subject - specifies the bank or payment service provider */
    channelSubject: SwiftpayPesonetInfo.ChannelSubject;
    extendInfo: SwiftpayPesonetInfo.ExtendInfo;
}

export namespace SwiftpayPesonetInfo {
    /** Channel subject - specifies the bank or payment service provider */
    export const ChannelSubject = {
        Alamanah: "alamanah",
        Allbank: "allbank",
        Anz: "anz",
        Guinobatan: "guinobatan",
        Aub: "aub",
        BangkoKabayan: "bangko_kabayan",
        Bangkomabuhay: "bangkomabuhay",
        NuestraSenora: "nuestra_senora",
        Bangkokbank: "bangkokbank",
        Bankofamerica: "bankofamerica",
        Bankofchina: "bankofchina",
        Bankofcommerce: "bankofcommerce",
        Bofz: "bofz",
        Bpibanko: "bpibanko",
        Bdouni: "bdouni",
        Bpi: "bpi",
        Camalig: "camalig",
        Cantilan: "cantilan",
        Cathay: "cathay",
        Chinabank: "chinabank",
        Chinabanksavings: "chinabanksavings",
        Citi: "citi",
        Ctbc: "ctbc",
        Coins: "coins",
        Deutsche: "deutsche",
        Dbp: "dbp",
        Dumaguetebankx: "dumaguetebankx",
        Dungganon: "dungganon",
        Eastwest: "eastwest",
        Equicom: "equicom",
        FirstConsolidated: "first_consolidated",
        Gcash: "gcash",
        Guagua: "guagua",
        Ibk: "ibk",
        Jpmorgan: "jpmorgan",
        Kebhana: "kebhana",
        LagunaPrestige: "laguna_prestige",
        Landbank: "landbank",
        Malayan: "malayan",
        Mayabank: "mayabank",
        Maybank: "maybank",
        Megaintl: "megaintl",
        Metrobank: "metrobank",
        Mizuho: "mizuho",
        Moneymall: "moneymall",
        Mufg: "mufg",
        Netbank: "netbank",
        Paymaya: "paymaya",
        PayMongo: "PayMongo",
        Pbcom: "pbcom",
        Veterans: "veterans",
        Philtrust: "philtrust",
        Pnb: "pnb",
        Producers: "producers",
        Psbank: "psbank",
        Queenbank: "queenbank",
        Rangay: "rangay",
        Rbtbank: "rbtbank",
        Rcbc: "rcbc",
        Robinsons: "robinsons",
        Digos: "digos",
        Montalban: "montalban",
        Rosario: "rosario",
        Silay: "silay",
        Ignacia: "ignacia",
        Seabank: "seabank",
        Security: "security",
        Shinhan: "shinhan",
        Smbc: "smbc",
        StandardChartered: "standard_chartered",
        Sterling: "sterling",
        Tonik: "tonik",
        Unionbank: "unionbank",
        Uniondigital: "uniondigital",
        Uob: "uob",
        Wealth: "wealth",
        Yuanta: "yuanta",
    } as const;
    export type ChannelSubject = (typeof ChannelSubject)[keyof typeof ChannelSubject];

    export interface ExtendInfo {
        /** Recipient account number */
        recipientAccountNumber: string;
        /** Recipient name */
        recipientName: string;
        /** Recipient address */
        recipientAddress?: string | undefined;
        /** Remarks */
        remarks?: string | undefined;
    }
}
