// This file was auto-generated by Fern from our API Definition.

export interface TooManyRequestsErrorBody {
    error?: TooManyRequestsErrorBody.Error_ | undefined;
    /** Unique request identifier for debugging */
    requestId?: number | undefined;
}

export namespace TooManyRequestsErrorBody {
    export interface Error_ {
        CODE: string;
        MESSAGE: string;
        DETAILS?: Error_.Details | undefined;
    }

    export namespace Error_ {
        export interface Details {
            /** Milliseconds to wait before the next request is accepted */
            retryAfterMs?: number | undefined;
        }
    }
}
