// This file was auto-generated by Fern from our API Definition.

import type * as Mesta from "../index.js";

export interface VirtualAccountSetupEnvelope {
    data: Mesta.VirtualAccountSetupResponse;
    /** Trace identifier for support and debugging. This is not a setup-request ID. */
    requestId: number;
}
