// This file was auto-generated by Fern from our API Definition.

export interface ListSourceWalletAddressesResponse {
    data?: ListSourceWalletAddressesResponse.Data.Item[] | undefined;
    /** Unique identifier for the API request */
    requestId?: number | undefined;
    /** Total number of records */
    total?: number | undefined;
    /** Whether there are more pages */
    hasNext?: boolean | undefined;
}

export namespace ListSourceWalletAddressesResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            id?: string | undefined;
            address?: string | undefined;
            chain?: Item.Chain | undefined;
            ownerId?: string | undefined;
            ownerType?: Item.OwnerType | undefined;
            riskLevel?: Item.RiskLevel | undefined;
            merchantId?: string | undefined;
            isWhitelistedOnProviders?: boolean | undefined;
            createdAt?: string | undefined;
            updatedAt?: string | undefined;
            /** Version number of the record */
            version?: number | undefined;
        }

        export namespace Item {
            export const Chain = {
                Ethereum: "ethereum",
                Polygon: "polygon",
                Solana: "solana",
                Tron: "tron",
                Stellar: "stellar",
            } as const;
            export type Chain = (typeof Chain)[keyof typeof Chain];
            export const OwnerType = {
                Merchant: "merchant",
                Sender: "sender",
                Organization: "organization",
            } as const;
            export type OwnerType = (typeof OwnerType)[keyof typeof OwnerType];
            export const RiskLevel = {
                Low: "low",
                Medium: "medium",
                High: "high",
                Critical: "critical",
            } as const;
            export type RiskLevel = (typeof RiskLevel)[keyof typeof RiskLevel];
        }
    }
}
