// This file was auto-generated by Fern from our API Definition.

export const ListQuotesRequestSortBy = {
    CreatedAt: "createdAt",
    UpdatedAt: "updatedAt",
} as const;
export type ListQuotesRequestSortBy = (typeof ListQuotesRequestSortBy)[keyof typeof ListQuotesRequestSortBy];
