// This file was auto-generated by Fern from our API Definition.

import type * as Mesta from "../../../../../index.js";

export interface GetFiatDepositsResponse {
    data?: Mesta.FiatDepositDetail | undefined;
    /** Unique identifier for the API request */
    requestId?: number | undefined;
}
