// This file was auto-generated by Fern from our API Definition.

export const ListFiatDepositsRequestCurrency = {
    Usd: "USD",
    Eur: "EUR",
    Gbp: "GBP",
    Mxn: "MXN",
    Brl: "BRL",
} as const;
export type ListFiatDepositsRequestCurrency =
    (typeof ListFiatDepositsRequestCurrency)[keyof typeof ListFiatDepositsRequestCurrency];
