// This file was auto-generated by Fern from our API Definition.

export interface GetDepositBankAccountOrdersResponse {
    data?: GetDepositBankAccountOrdersResponse.Data | undefined;
    /** Unique identifier for the API request */
    requestId?: number | undefined;
}

export namespace GetDepositBankAccountOrdersResponse {
    export interface Data {
        /** Account holder name */
        name?: string | undefined;
        /** Account holder address */
        address?: string | undefined;
        /** Bank account number */
        accountNumber?: string | undefined;
        /** Reference to use for the deposit */
        reference?: string | undefined;
        bankDetails?: Data.BankDetails | undefined;
        /** SWIFT/BIC code for the bank */
        bic?: string | undefined;
        /** Payment provider name (e.g., 'openpayd', 'bcb') */
        provider?: string | undefined;
        /** Provider's reference identifier for this account */
        providerReferenceId?: string | undefined;
        /** Sort code for GBP bank accounts */
        sortCode?: string | undefined;
        /** Routing details for the bank account. Present for USD wire transfers. */
        routingDetails?: Data.RoutingDetails.Item[] | undefined;
    }

    export namespace Data {
        export interface BankDetails {
            /** Bank name */
            name?: string | undefined;
            /** Bank address */
            address?: string | undefined;
        }

        export type RoutingDetails = RoutingDetails.Item[];

        export namespace RoutingDetails {
            export interface Item {
                /** Transfer type for this routing entry */
                transferType?: string | undefined;
                /** Routing number */
                routingNumber?: string | undefined;
            }
        }
    }
}
