// This file was auto-generated by Fern from our API Definition.

import type * as Mesta from "../../../index.js";

export type CreateV1SendersRequest = Mesta.CreateV1SendersRequest.Individual | Mesta.CreateV1SendersRequest.Business;

export namespace CreateV1SendersRequest {
    export interface Individual extends Mesta.IndividualSender {
        type: "individual";
    }

    export interface Business extends Mesta.BusinessSender {
        type: "business";
    }
}
