// This file was auto-generated by Fern from our API Definition.

export const ListSendersRequestSortBy = {
    CreatedAt: "createdAt",
    UpdatedAt: "updatedAt",
} as const;
export type ListSendersRequestSortBy = (typeof ListSendersRequestSortBy)[keyof typeof ListSendersRequestSortBy];
