// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface UpdateApiKeysRequest {
    /** ID of the API key */
    id: string;
    /** Updated name for the API key */
    name?: string;
    /** Updated list of permissions */
    permissions?: string[];
}
