// This file was auto-generated by Fern from our API Definition.

import type * as Mesta from "../../../../index.js";

/**
 * @example
 *     {
 *         type: "individual",
 *         address: {
 *             street: "123 Main St",
 *             city: "Manila",
 *             postalCode: "1000",
 *             country: "PH"
 *         },
 *         paymentMethods: [{
 *                 type: "bank_account",
 *                 data: {
 *                     "key": "value"
 *                 }
 *             }]
 *     }
 */
export interface CreateV2BeneficiariesRequest {
    /** Type of beneficiary */
    type: CreateV2BeneficiariesRequest.Type;
    /** First name (required for individual type) */
    firstName?: string;
    /** Last name (required for individual type) */
    lastName?: string;
    /** Middle name (optional, individual type only) */
    middleName?: string;
    /** Full business name (required for business type) */
    fullName?: string;
    /** Business registration number (required for business type) */
    businessRegistrationNumber?: string;
    /** Type of business (optional) */
    businessType?: CreateV2BeneficiariesRequest.BusinessType;
    /** Beneficiary email */
    email?: string;
    /** Beneficiary phone number */
    phone?: string;
    /** Date of birth (YYYY-MM-DD, individual type) */
    birthDate?: string;
    /** Merchant ID (optional, auto-assigned from API key) */
    merchantId?: string;
    /** Beneficiary address */
    address: CreateV2BeneficiariesRequest.Address;
    /** Identity document details */
    identity?: CreateV2BeneficiariesRequest.Identity;
    /** At least one payment method must be provided */
    paymentMethods: CreateV2BeneficiariesRequest.PaymentMethods.Item[];
    /** Custom metadata */
    metadata?: Record<string, unknown>;
    beneficiaryRelationship?: Mesta.BeneficiaryRelationship;
    purposeOfPayment?: Mesta.PurposeOfPayment;
    purposeOfPaymentDocument?: Mesta.PurposeOfPaymentDocumentRequest;
}

export namespace CreateV2BeneficiariesRequest {
    /** Type of beneficiary */
    export const Type = {
        Individual: "individual",
        Business: "business",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    /** Type of business (optional) */
    export const BusinessType = {
        SoleProprietorship: "sole_proprietorship",
        Corporation: "corporation",
        LimitedLiabilityCompany: "limited_liability_company",
        Partnership: "partnership",
        Other: "other",
    } as const;
    export type BusinessType = (typeof BusinessType)[keyof typeof BusinessType];

    /**
     * Beneficiary address
     */
    export interface Address {
        /** Street address */
        street: string;
        /** Additional address line */
        street2?: string | undefined;
        /** City */
        city: string;
        /** State code (ISO 3166-2 format) */
        state?: string | undefined;
        /** Postal code (min 5 characters) */
        postalCode: string;
        /** Country code (ISO 3166-1 alpha-2) */
        country: string;
    }

    /**
     * Identity document details
     */
    export interface Identity {
        /** Type of identity document */
        documentType?: Identity.DocumentType | undefined;
        /** Document number */
        documentNumber?: string | undefined;
        /** Issue date */
        issueDate?: string | undefined;
        /** Expiry date */
        expiryDate?: string | undefined;
        /** Issuing authority */
        issuer?: string | undefined;
    }

    export namespace Identity {
        /** Type of identity document */
        export const DocumentType = {
            Passport: "PASSPORT",
            DriverLicense: "DRIVER_LICENSE",
            NationalId: "NATIONAL_ID",
            IdCard: "ID_CARD",
            ResidentCard: "RESIDENT_CARD",
            VoterIdCard: "VOTER_ID_CARD",
            TaxId: "TAX_ID",
        } as const;
        export type DocumentType = (typeof DocumentType)[keyof typeof DocumentType];
    }

    export type PaymentMethods = PaymentMethods.Item[];

    export namespace PaymentMethods {
        export interface Item {
            type: Mesta.PaymentMethodType;
            /** Payment method data. Structure depends on type. */
            data: Record<string, unknown>;
            /** Display label */
            label?: string | undefined;
        }
    }
}
