// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface GetV2BeneficiariesRequest {
    /** Beneficiary ID */
    id: string;
}
