// This file was auto-generated by Fern from our API Definition.

import type * as Mesta from "../../../../index.js";

/**
 * @example
 *     {
 *         merchantId: "xxxxxxxx-xxxx-4xxx-xxxx-xxxxxxxxxxxx"
 *     }
 */
export interface ListV1BeneficiariesRequest {
    /** Filter beneficiaries by ID */
    id?: string;
    /** Identifier of the associated merchant */
    merchantId?: string;
    /** Filter beneficiaries by verification status */
    status?: Mesta.ListV1BeneficiariesRequestStatus;
    /** Page number for pagination */
    page?: number;
    /** Number of items per page */
    pageSize?: number;
    /** Field to sort the beneficiaries by */
    sortBy?: string;
    /** Sort order (ascending or descending) */
    sortOrder?: Mesta.ListV1BeneficiariesRequestSortOrder;
}
