// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         countryCode: "countryCode"
 *     }
 */
export interface LookupBankBeneficiariesRequest {
    /** ISO 3166-1 alpha-2 country code */
    countryCode: string;
}
