// This file was auto-generated by Fern from our API Definition.

import type * as Mesta from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id",
 *         type: "bank_account",
 *         data: {
 *             accountNumber: "1234567890"
 *         }
 *     }
 */
export interface UpdatePaymentMethodRequest {
    /** Payment method ID */
    id: string;
    type: Mesta.PaymentMethodType;
    /** Payment method data. Structure depends on the type field. */
    data: UpdatePaymentMethodRequest.Data;
    /** Display label for the payment method */
    label?: string;
    /** Whether user consent is required before approval */
    requiresUserConsent?: boolean;
}

export namespace UpdatePaymentMethodRequest {
    /**
     * Payment method data. Structure depends on the type field.
     */
    export type Data =
        | Mesta.BankAccountInfo
        | Mesta.PixInfo
        | Mesta.InstapayInfo
        | Mesta.SwiftpayPesonetInfo
        | Mesta.SpeiInfo
        | Mesta.MobileMoneyInfo
        | Mesta.CryptoWalletInfo;
}
