// This file was auto-generated by Fern from our API Definition.

export const ListFiatDepositsRequestSortOrder = {
    Asc: "ASC",
    Desc: "DESC",
} as const;
export type ListFiatDepositsRequestSortOrder =
    (typeof ListFiatDepositsRequestSortOrder)[keyof typeof ListFiatDepositsRequestSortOrder];
