// This file was auto-generated by Fern from our API Definition.

import * as Mesta from "../../src/api/index";
import { MestaClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("BeneficiariesClient", () => {
    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { requestId: 19052 };

        server
            .mockEndpoint()
            .delete("/v1/beneficiaries/beneficiaryId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.beneficiaries.delete({
            beneficiaryId: "beneficiaryId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/v1/beneficiaries/beneficiaryId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.beneficiaries.delete({
                beneficiaryId: "beneficiaryId",
            });
        }).rejects.toThrow(Mesta.UnauthorizedError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/v1/beneficiaries/beneficiaryId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.beneficiaries.delete({
                beneficiaryId: "beneficiaryId",
            });
        }).rejects.toThrow(Mesta.ForbiddenError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/v1/beneficiaries/beneficiaryId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.beneficiaries.delete({
                beneficiaryId: "beneficiaryId",
            });
        }).rejects.toThrow(Mesta.NotFoundError);
    });

    test("delete (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .delete("/v1/beneficiaries/beneficiaryId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.beneficiaries.delete({
                beneficiaryId: "beneficiaryId",
            });
        }).rejects.toThrow(Mesta.InternalServerError);
    });

    test("simulateVerificationResult (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { result: "APPROVED" };
        const rawResponseBody = { requestId: 1 };

        server
            .mockEndpoint()
            .post("/v1/beneficiaries/beneficiaryId/mock-verification-result")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.beneficiaries.simulateVerificationResult({
            beneficiaryId: "beneficiaryId",
            result: "APPROVED",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("simulateVerificationResult (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { result: "APPROVED" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/beneficiaries/beneficiaryId/mock-verification-result")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.beneficiaries.simulateVerificationResult({
                beneficiaryId: "beneficiaryId",
                result: "APPROVED",
            });
        }).rejects.toThrow(Mesta.BadRequestError);
    });

    test("simulateVerificationResult (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { result: "APPROVED" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/beneficiaries/beneficiaryId/mock-verification-result")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.beneficiaries.simulateVerificationResult({
                beneficiaryId: "beneficiaryId",
                result: "APPROVED",
            });
        }).rejects.toThrow(Mesta.UnauthorizedError);
    });

    test("simulateVerificationResult (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { result: "APPROVED" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/beneficiaries/beneficiaryId/mock-verification-result")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.beneficiaries.simulateVerificationResult({
                beneficiaryId: "beneficiaryId",
                result: "APPROVED",
            });
        }).rejects.toThrow(Mesta.ForbiddenError);
    });

    test("simulateVerificationResult (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { result: "APPROVED" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/beneficiaries/beneficiaryId/mock-verification-result")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.beneficiaries.simulateVerificationResult({
                beneficiaryId: "beneficiaryId",
                result: "APPROVED",
            });
        }).rejects.toThrow(Mesta.NotFoundError);
    });

    test("verify (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { requestId: 19052 };

        server
            .mockEndpoint()
            .post("/v1/beneficiaries/beneficiaryId/verify")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.beneficiaries.verify({
            beneficiaryId: "beneficiaryId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("verify (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/beneficiaries/beneficiaryId/verify")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.beneficiaries.verify({
                beneficiaryId: "beneficiaryId",
            });
        }).rejects.toThrow(Mesta.BadRequestError);
    });

    test("verify (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/beneficiaries/beneficiaryId/verify")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.beneficiaries.verify({
                beneficiaryId: "beneficiaryId",
            });
        }).rejects.toThrow(Mesta.UnauthorizedError);
    });

    test("verify (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/beneficiaries/beneficiaryId/verify")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.beneficiaries.verify({
                beneficiaryId: "beneficiaryId",
            });
        }).rejects.toThrow(Mesta.ForbiddenError);
    });

    test("verify (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/beneficiaries/beneficiaryId/verify")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.beneficiaries.verify({
                beneficiaryId: "beneficiaryId",
            });
        }).rejects.toThrow(Mesta.NotFoundError);
    });

    test("verify (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/v1/beneficiaries/beneficiaryId/verify")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.beneficiaries.verify({
                beneficiaryId: "beneficiaryId",
            });
        }).rejects.toThrow(Mesta.InternalServerError);
    });

    test("lookupBank (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [{ id: "id", name: "Example Bank plc", supportedAccountTypes: ["supportedAccountTypes"] }],
            requestId: 40538,
        };

        server
            .mockEndpoint()
            .get("/v1/beneficiaries/banks")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.beneficiaries.lookupBank({
            countryCode: "countryCode",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("lookupBank (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/beneficiaries/banks")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.beneficiaries.lookupBank({
                countryCode: "countryCode",
            });
        }).rejects.toThrow(Mesta.BadRequestError);
    });

    test("lookupBank (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/beneficiaries/banks")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.beneficiaries.lookupBank({
                countryCode: "countryCode",
            });
        }).rejects.toThrow(Mesta.UnauthorizedError);
    });

    test("lookupBank (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/beneficiaries/banks")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.beneficiaries.lookupBank({
                countryCode: "countryCode",
            });
        }).rejects.toThrow(Mesta.ForbiddenError);
    });

    test("lookupBank (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/v1/beneficiaries/banks")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.beneficiaries.lookupBank({
                countryCode: "countryCode",
            });
        }).rejects.toThrow(Mesta.InternalServerError);
    });

    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    id: "id",
                    type: "individual",
                    firstName: "firstName",
                    middleName: "middleName",
                    lastName: "lastName",
                    fullName: "fullName",
                    birthDate: "2023-01-15",
                    email: "email",
                    phone: "phone",
                    merchantId: "merchantId",
                    status: "active",
                    businessType: "sole_proprietorship",
                    businessRegistrationNumber: "businessRegistrationNumber",
                    metadata: { key: "value" },
                    createdAt: "2024-01-15T09:30:00Z",
                    updatedAt: "2024-01-15T09:30:00Z",
                    version: 1,
                    beneficiaryRelationship: "business_partner",
                    purposeOfPayment: "payroll",
                },
            ],
            total: 1,
            hasNext: true,
            requestId: 1,
        };

        server.mockEndpoint().get("/v2/beneficiaries").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.beneficiaries.list();
        expect(response).toEqual(rawResponseBody);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v2/beneficiaries").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.beneficiaries.list();
        }).rejects.toThrow(Mesta.UnauthorizedError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v2/beneficiaries").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.beneficiaries.list();
        }).rejects.toThrow(Mesta.ForbiddenError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server.mockEndpoint().get("/v2/beneficiaries").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.beneficiaries.list();
        }).rejects.toThrow(Mesta.InternalServerError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: {
                id: "id",
                type: "individual",
                firstName: "firstName",
                middleName: "middleName",
                lastName: "lastName",
                fullName: "fullName",
                birthDate: "2023-01-15",
                email: "email",
                phone: "phone",
                address: {
                    street: "street",
                    street2: "street2",
                    city: "city",
                    state: "state",
                    postalCode: "postalCode",
                    country: "country",
                },
                merchantId: "merchantId",
                verification: { status: "unverified", statusUpdatedAt: "2024-01-15T09:30:00Z" },
                status: "active",
                identity: {
                    documentType: "PASSPORT",
                    documentNumber: "documentNumber",
                    issueDate: "2023-01-15",
                    expiryDate: "2023-01-15",
                    issuer: "issuer",
                    countryCode: "countryCode",
                },
                businessType: "sole_proprietorship",
                businessRegistrationNumber: "businessRegistrationNumber",
                paymentMethods: [
                    {
                        id: "550e8400-e29b-41d4-a716-446655440000",
                        beneficiaryId: "550e8400-e29b-41d4-a716-446655440001",
                        merchantId: "550e8400-e29b-41d4-a716-446655440002",
                        label: "My US Bank Account",
                        data: {
                            type: "bank_account",
                            accountNumber: "1234567890",
                            ifscCode: "EXAM0001234",
                            bic: "EXMPGB2L",
                            sortCode: "123456",
                            routingNumber: "011401533",
                            bsbNumber: "012345",
                            bankName: "Sample Bank",
                        },
                        createdAt: "2025-01-15T10:30:00Z",
                        updatedAt: "2025-01-15T10:30:00Z",
                    },
                ],
                metadata: { key: "value" },
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
                version: 1,
                beneficiaryRelationship: "business_partner",
                purposeOfPayment: "payroll",
                purposeOfPaymentDocument: {
                    id: "id",
                    fileName: "fileName",
                    type: "type",
                    submittedAt: "2024-01-15T09:30:00Z",
                },
            },
            requestId: 1,
        };

        server
            .mockEndpoint()
            .get("/v2/beneficiaries/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.beneficiaries.get({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v2/beneficiaries/id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.beneficiaries.get({
                id: "id",
            });
        }).rejects.toThrow(Mesta.UnauthorizedError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v2/beneficiaries/id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.beneficiaries.get({
                id: "id",
            });
        }).rejects.toThrow(Mesta.ForbiddenError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v2/beneficiaries/id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.beneficiaries.get({
                id: "id",
            });
        }).rejects.toThrow(Mesta.NotFoundError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/v2/beneficiaries/id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.beneficiaries.get({
                id: "id",
            });
        }).rejects.toThrow(Mesta.InternalServerError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { data: { key: "value" }, requestId: 1 };

        server
            .mockEndpoint()
            .patch("/v2/beneficiaries/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.beneficiaries.update({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v2/beneficiaries/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.beneficiaries.update({
                id: "id",
            });
        }).rejects.toThrow(Mesta.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v2/beneficiaries/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.beneficiaries.update({
                id: "id",
            });
        }).rejects.toThrow(Mesta.UnauthorizedError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v2/beneficiaries/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.beneficiaries.update({
                id: "id",
            });
        }).rejects.toThrow(Mesta.ForbiddenError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v2/beneficiaries/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.beneficiaries.update({
                id: "id",
            });
        }).rejects.toThrow(Mesta.NotFoundError);
    });

    test("update (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .patch("/v2/beneficiaries/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.beneficiaries.update({
                id: "id",
            });
        }).rejects.toThrow(Mesta.InternalServerError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            type: "individual",
            address: { street: "123 Main St", city: "Manila", postalCode: "1000", country: "PH" },
            paymentMethods: [{ type: "bank_account", data: { key: "value" } }],
            beneficiaryRelationship: "business_partner",
            purposeOfPayment: "payroll",
        };
        const rawResponseBody = {
            data: {
                id: "id",
                type: "individual",
                firstName: "firstName",
                middleName: "middleName",
                lastName: "lastName",
                fullName: "fullName",
                birthDate: "2023-01-15",
                email: "email",
                phone: "phone",
                address: {
                    street: "street",
                    street2: "street2",
                    city: "city",
                    state: "state",
                    postalCode: "postalCode",
                    country: "country",
                },
                merchantId: "merchantId",
                verification: { status: "unverified", statusUpdatedAt: "2024-01-15T09:30:00Z" },
                status: "active",
                identity: {
                    documentType: "PASSPORT",
                    documentNumber: "documentNumber",
                    issueDate: "2023-01-15",
                    expiryDate: "2023-01-15",
                    issuer: "issuer",
                },
                businessType: "sole_proprietorship",
                businessRegistrationNumber: "businessRegistrationNumber",
                paymentMethods: [
                    {
                        id: "550e8400-e29b-41d4-a716-446655440000",
                        beneficiaryId: "550e8400-e29b-41d4-a716-446655440001",
                        merchantId: "550e8400-e29b-41d4-a716-446655440002",
                        label: "My US Bank Account",
                        data: {
                            type: "bank_account",
                            accountNumber: "1234567890",
                            ifscCode: "EXAM0001234",
                            bic: "EXMPGB2L",
                            sortCode: "123456",
                            routingNumber: "011401533",
                            bsbNumber: "012345",
                            bankName: "Sample Bank",
                        },
                        createdAt: "2025-01-15T10:30:00Z",
                        updatedAt: "2025-01-15T10:30:00Z",
                    },
                ],
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
                version: 1,
            },
            requestId: 1,
        };

        server
            .mockEndpoint()
            .post("/v3/beneficiaries")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.beneficiaries.create({
            type: "individual",
            address: {
                street: "123 Main St",
                city: "Manila",
                postalCode: "1000",
                country: "PH",
            },
            paymentMethods: [
                {
                    type: "bank_account",
                    data: {
                        key: "value",
                    },
                },
            ],
            beneficiaryRelationship: "business_partner",
            purposeOfPayment: "payroll",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            type: "individual",
            address: { street: "street", city: "city", postalCode: "postalCode", country: "country" },
            paymentMethods: [
                { type: "bank_account", data: { data: { key: "value" } } },
                { type: "bank_account", data: { data: { key: "value" } } },
            ],
            beneficiaryRelationship: "business_partner",
            purposeOfPayment: "payroll",
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v3/beneficiaries")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.beneficiaries.create({
                type: "individual",
                address: {
                    street: "street",
                    city: "city",
                    postalCode: "postalCode",
                    country: "country",
                },
                paymentMethods: [
                    {
                        type: "bank_account",
                        data: {
                            data: {
                                key: "value",
                            },
                        },
                    },
                    {
                        type: "bank_account",
                        data: {
                            data: {
                                key: "value",
                            },
                        },
                    },
                ],
                beneficiaryRelationship: "business_partner",
                purposeOfPayment: "payroll",
            });
        }).rejects.toThrow(Mesta.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            type: "individual",
            address: { street: "street", city: "city", postalCode: "postalCode", country: "country" },
            paymentMethods: [
                { type: "bank_account", data: { data: { key: "value" } } },
                { type: "bank_account", data: { data: { key: "value" } } },
            ],
            beneficiaryRelationship: "business_partner",
            purposeOfPayment: "payroll",
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v3/beneficiaries")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.beneficiaries.create({
                type: "individual",
                address: {
                    street: "street",
                    city: "city",
                    postalCode: "postalCode",
                    country: "country",
                },
                paymentMethods: [
                    {
                        type: "bank_account",
                        data: {
                            data: {
                                key: "value",
                            },
                        },
                    },
                    {
                        type: "bank_account",
                        data: {
                            data: {
                                key: "value",
                            },
                        },
                    },
                ],
                beneficiaryRelationship: "business_partner",
                purposeOfPayment: "payroll",
            });
        }).rejects.toThrow(Mesta.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            type: "individual",
            address: { street: "street", city: "city", postalCode: "postalCode", country: "country" },
            paymentMethods: [
                { type: "bank_account", data: { data: { key: "value" } } },
                { type: "bank_account", data: { data: { key: "value" } } },
            ],
            beneficiaryRelationship: "business_partner",
            purposeOfPayment: "payroll",
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v3/beneficiaries")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.beneficiaries.create({
                type: "individual",
                address: {
                    street: "street",
                    city: "city",
                    postalCode: "postalCode",
                    country: "country",
                },
                paymentMethods: [
                    {
                        type: "bank_account",
                        data: {
                            data: {
                                key: "value",
                            },
                        },
                    },
                    {
                        type: "bank_account",
                        data: {
                            data: {
                                key: "value",
                            },
                        },
                    },
                ],
                beneficiaryRelationship: "business_partner",
                purposeOfPayment: "payroll",
            });
        }).rejects.toThrow(Mesta.ForbiddenError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new MestaClient({
            maxRetries: 0,
            apiKey: "test",
            apiSecret: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {
            type: "individual",
            address: { street: "street", city: "city", postalCode: "postalCode", country: "country" },
            paymentMethods: [
                { type: "bank_account", data: { data: { key: "value" } } },
                { type: "bank_account", data: { data: { key: "value" } } },
            ],
            beneficiaryRelationship: "business_partner",
            purposeOfPayment: "payroll",
        };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/v3/beneficiaries")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.beneficiaries.create({
                type: "individual",
                address: {
                    street: "street",
                    city: "city",
                    postalCode: "postalCode",
                    country: "country",
                },
                paymentMethods: [
                    {
                        type: "bank_account",
                        data: {
                            data: {
                                key: "value",
                            },
                        },
                    },
                    {
                        type: "bank_account",
                        data: {
                            data: {
                                key: "value",
                            },
                        },
                    },
                ],
                beneficiaryRelationship: "business_partner",
                purposeOfPayment: "payroll",
            });
        }).rejects.toThrow(Mesta.InternalServerError);
    });
});
