// This file was auto-generated by Fern from our API Definition.

import type * as Mesta from "../../../../index.js";

/**
 * @example
 *     {
 *         acceptedQuoteId: "acceptedQuoteId",
 *         senderId: "senderId",
 *         beneficiaryId: "beneficiaryId"
 *     }
 */
export interface CreateV1OrdersRequest {
    /** Unique ID for the quote to use for this order. */
    acceptedQuoteId: string;
    /** Unique identifier for the sender. */
    senderId: string;
    /** Unique identifier for the beneficiary. */
    beneficiaryId: string;
    purpose?: Mesta.Purpose;
    /** Custom metadata to attach to the order */
    metadata?: Record<string, unknown>;
    sourceOfFunds?: Mesta.SourceOfFunds;
    beneficiaryRelationship?: Mesta.BeneficiaryRelationship;
    /** Optional array of supporting documents */
    documents?: Mesta.OrderDocumentInput[];
    /** Your internal reference ID for this order */
    customerReferenceId?: string;
}
