// This file was auto-generated by Fern from our API Definition.

import type * as Mesta from "../../../../index.js";

/**
 * @example
 *     {
 *         senderId: "550e8400-e29b-41d4-a716-446655440001",
 *         paymentMethodId: "550e8400-e29b-41d4-a716-446655440002",
 *         acceptedQuoteId: "550e8400-e29b-41d4-a716-446655440003"
 *     }
 */
export interface CreateOrdersRequest {
    /** ID of the sender initiating the order */
    senderId: string;
    /** ID of the payment method to use for delivery */
    paymentMethodId: string;
    /** ID of the accepted quote */
    acceptedQuoteId: string;
    /** Purpose of payment for the order. Required if the beneficiary does not have a purpose of payment configured during onboarding. */
    purpose?: Mesta.Purpose;
    /** Custom metadata to attach to the order */
    metadata?: Record<string, unknown>;
    /** Beneficiary relationship for the order. Required if the beneficiary does not have a beneficiary relationship configured during onboarding. */
    beneficiaryRelationship?: Mesta.BeneficiaryRelationship;
    /** Source of funds for the order. Required if the sender does not have a source of funds configured during onboarding. */
    sourceOfFunds?: Mesta.SourceOfFunds;
    /** Supporting documents for the order. Required if the beneficiary does not have a purpose of payment document on file. */
    documents?: Mesta.OrderDocumentInput[];
    /** Your internal reference ID for this order */
    customerReferenceId?: string;
    /** Declaration that the funds belong to the sender. */
    sendersOwnFunds?: boolean;
    /** Optional. When true, the order is funded from your pooled merchant account balance instead of the sender’s individual wallet. The order still belongs to the sender and the payout runs in the sender’s name — only the funding source changes. Supported for stablecoin-source orders. Pooled Merchant Accounts is available to select merchants only — please reach out to Mesta support to have it enabled for your account. */
    usePooledFunds?: boolean;
}
