// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         orderId: "orderId"
 *     }
 */
export interface ListEventsOrdersRequest {
    /** Order ID */
    orderId: string;
}
