// This file was auto-generated by Fern from our API Definition.

import type * as Mesta from "../../../../../../index.js";

/**
 * @example
 *     {
 *         search: "abc123",
 *         merchantId: "550e8400-e29b-41d4-a716-446655440000",
 *         senderId: "550e8400-e29b-41d4-a716-446655440001",
 *         depositBankAccountId: "550e8400-e29b-41d4-a716-446655440002"
 *     }
 */
export interface ListFiatDepositsRequest {
    /** Page number (0-indexed) */
    page?: number;
    /** Number of records per page */
    pageSize?: number;
    /** Sort column */
    sortBy?: Mesta.merchants.ListFiatDepositsRequestSortBy;
    /** Sort order */
    sortOrder?: Mesta.merchants.ListFiatDepositsRequestSortOrder;
    /** Search query */
    search?: string;
    /** Filter by fiat currency */
    currency?: Mesta.merchants.ListFiatDepositsRequestCurrency;
    /** Filter by merchant ID */
    merchantId?: string;
    /** Filter by sender ID */
    senderId?: string;
    /** Filter by deposit bank account ID */
    depositBankAccountId?: string;
}
