// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface GenerateLedgerAccountsSendersRequest {
    /** ID of the sender */
    id: string;
}
