// This file was auto-generated by Fern from our API Definition.

import type * as Mesta from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListSendersRequest {
    /** Filter senders by specific ID */
    id?: string;
    /** Filter senders by their verification status */
    status?: Mesta.ListSendersRequestStatus;
    /** Records per page */
    pageSize?: number;
    /** Page number */
    page?: number;
    /** Sort column */
    sortBy?: Mesta.ListSendersRequestSortBy;
    /** Sort order */
    sortOrder?: Mesta.ListSendersRequestSortOrder;
}
