// This file was auto-generated by Fern from our API Definition.

export interface DeletePaymentMethodsResponse {
    /** Empty response on successful deletion */
    data?: Record<string, unknown> | undefined;
    /** Unique identifier for the API request */
    requestId?: number | undefined;
}
