// This file was auto-generated by Fern from our API Definition.

export const ListPaymentMethodsRequestSortBy = {
    CreatedAt: "createdAt",
    UpdatedAt: "updatedAt",
} as const;
export type ListPaymentMethodsRequestSortBy =
    (typeof ListPaymentMethodsRequestSortBy)[keyof typeof ListPaymentMethodsRequestSortBy];
