// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         orderId: "orderId",
 *         documentId: "documentId"
 *     }
 */
export interface GetPresignedUrlDocumentsRequest {
    /** ID of the order */
    orderId: string;
    /** ID of the document */
    documentId: string;
}
