// This file was auto-generated by Fern from our API Definition.

export interface AcceptTermsOfServiceResponse {
    data?: AcceptTermsOfServiceResponse.Data | undefined;
    /** Unique identifier for the API request */
    requestId?: number | undefined;
}

export namespace AcceptTermsOfServiceResponse {
    export interface Data {
        /** Unique identifier for the TOS acceptance record */
        id?: string | undefined;
        /** ID of the sender */
        senderId?: string | undefined;
        /** ID of the merchant */
        merchantId?: string | undefined;
        /** Version of the TOS that was accepted */
        tosVersion?: string | undefined;
        /** Timestamp when the TOS was accepted */
        acceptedAt?: string | undefined;
        /** IP address of the client that accepted */
        ipAddress?: string | undefined;
        /** User agent of the client that accepted */
        userAgent?: string | undefined;
    }
}
