// This file was auto-generated by Fern from our API Definition.

export interface CreateLinkTermsOfServiceResponse {
    data?: CreateLinkTermsOfServiceResponse.Data | undefined;
    /** Unique identifier for the API request */
    requestId?: number | undefined;
}

export namespace CreateLinkTermsOfServiceResponse {
    export interface Data {
        /** Current TOS acceptance status */
        status?: Data.Status | undefined;
        /** When the TOS was accepted */
        acceptedAt?: (string | null) | undefined;
        /** TOS version */
        version?: string | undefined;
        /** Unique identifier for the TOS acceptance record */
        agreementId?: string | undefined;
        /** Full URL for the TOS acceptance page */
        tosLink?: string | undefined;
        /** Unique token for this TOS acceptance */
        token?: string | undefined;
        /** When the TOS link expires */
        expiresAt?: string | undefined;
        /** Name of the sender */
        senderName?: string | undefined;
        /** Email of the sender */
        senderEmail?: string | undefined;
        /** Name of the merchant */
        merchantName?: string | undefined;
        /** TOS version string */
        tosVersion?: string | undefined;
        /** Whether the TOS link has expired */
        isExpired?: boolean | undefined;
        /** Whether the TOS has been accepted */
        isAccepted?: boolean | undefined;
        /** When the TOS link was generated */
        generatedAt?: string | undefined;
    }

    export namespace Data {
        /** Current TOS acceptance status */
        export const Status = {
            Pending: "pending",
            Accepted: "accepted",
            Expired: "expired",
            NotRequired: "not_required",
        } as const;
        export type Status = (typeof Status)[keyof typeof Status];
    }
}
