// This file was auto-generated by Fern from our API Definition.

import type * as Mesta from "../../../index.js";

export type UpdateSendersRequestBody = Mesta.PatchIndividualSender | Mesta.PatchBusinessSender;
