// This file was auto-generated by Fern from our API Definition.

export const GetUboRulesV2SendersRequestOwnerType = {
    Business: "business",
} as const;
export type GetUboRulesV2SendersRequestOwnerType =
    (typeof GetUboRulesV2SendersRequestOwnerType)[keyof typeof GetUboRulesV2SendersRequestOwnerType];
