// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         sourceWalletAddressId: "sourceWalletAddressId"
 *     }
 */
export interface DeleteSourceWalletAddressesRequest {
    /** ID of the sender */
    id: string;
    /** ID of the source wallet address to delete */
    sourceWalletAddressId: string;
}
