// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         firstName: "firstName",
 *         lastName: "lastName",
 *         birthDate: "2023-01-15",
 *         phone: "phone",
 *         email: "email",
 *         ownershipPercent: 1.1,
 *         address: {
 *             street: "street",
 *             city: "city",
 *             postalCode: "12345 or 00000",
 *             country: "country"
 *         },
 *         senderId: "senderId",
 *         identity: {
 *             documentType: "PASSPORT",
 *             countryCode: "countryCode",
 *             documentNumber: "documentNumber"
 *         }
 *     }
 */
export interface CreateV1UbosRequest {
    /** First name of the UBO (Ultimate Beneficial Owner). */
    firstName: string;
    /** Last name of the UBO (Ultimate Beneficial Owner). */
    lastName: string;
    /** Birthdate of the UBO (Ultimate Beneficial Owner) in the format yyyy-mm-dd. */
    birthDate: string;
    /** Phone number of the UBO (Ultimate Beneficial Owner) in international format (e.g., +11234567890). */
    phone: string;
    /** Email address of the UBO (Ultimate Beneficial Owner). */
    email: string;
    /** Ownership percentage of the UBO in the company */
    ownershipPercent: number;
    /** UBO postal address. */
    address: CreateV1UbosRequest.Address;
    /** Unique identifier for the sender. */
    senderId: string;
    /** Ultimate Beneficial Owner information. Note: Document requirements (documentFront, documentBack) vary by country. Please refer to the validation-rules endpoint with ownerType='ubo' and the specific country to determine exact documentation requirements. */
    identity: CreateV1UbosRequest.Identity;
}

export namespace CreateV1UbosRequest {
    /**
     * UBO postal address.
     */
    export interface Address {
        /** UBO street address. */
        street: string;
        /** UBO street address line 2 (apartment, suite, unit, etc.) */
        street2?: string | undefined;
        /** UBO city. */
        city: string;
        /** UBO state or province. */
        state?: string | undefined;
        /** Postal/ZIP code. Use '00000' for countries without postal code systems */
        postalCode: string;
        /** UBO country. */
        country: string;
    }

    /**
     * Ultimate Beneficial Owner information. Note: Document requirements (documentFront, documentBack) vary by country. Please refer to the validation-rules endpoint with ownerType='ubo' and the specific country to determine exact documentation requirements.
     */
    export interface Identity {
        /** Type of identity document. */
        documentType: Identity.DocumentType;
        /** Country code of the identity document. */
        countryCode: string;
        /** Base64 encoded front image of identity document. Required for certain countries - check validation-rules endpoint. */
        documentFront?: string | undefined;
        /** Base64 encoded back image of identity document. Required for certain countries - check validation-rules endpoint. */
        documentBack?: string | undefined;
        /** The number of the selected documentType */
        documentNumber: string;
    }

    export namespace Identity {
        /** Type of identity document. */
        export const DocumentType = {
            Passport: "PASSPORT",
            DriverLicense: "DRIVER_LICENSE",
            NationalId: "NATIONAL_ID",
            IdCard: "ID_CARD",
            ResidentCard: "RESIDENT_CARD",
            VoterId: "VOTER_ID",
            VisaDocument: "VISA_DOCUMENT",
            VoterIdCard: "VOTER_ID_CARD",
            GhanaCard: "GHANA_CARD",
            GhanaSsnitCard: "GHANA_SSNIT_CARD",
            GreenBook: "GREEN_BOOK",
            ZaGreenBook: "ZA_GREEN_BOOK",
            KenyaAlienCard: "KENYA_ALIEN_CARD",
            PanCard: "PAN_CARD",
            TaxId: "TAX_ID",
            Ssnit: "SSNIT",
            AlienCard: "ALIEN_CARD",
            KenyaKraPin: "KENYA_KRA_PIN",
            Bvn: "BVN",
            Nin: "NIN",
            Ssn4: "SSN4",
            Ssn9: "SSN9",
            ColombiaPpt: "COLOMBIA_PPT",
            GhanaCardNumber: "GHANA_CARD_NUMBER",
            NinSlip: "NIN_SLIP",
            ResidentId: "RESIDENT_ID",
        } as const;
        export type DocumentType = (typeof DocumentType)[keyof typeof DocumentType];
    }
}
